src/main/java/com/nicmus/jpoweradmin/model/orm/Record.java
/*******************************************************************************
 * Copyright (C) 2019 nicmus inc. (jivko.sabev@gmail.com)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.nicmus.jpoweradmin.model.orm;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@Entity
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Record extends PersistentObject {
	private static final long serialVersionUID = 8356362271275690792L;

	public enum TYPE{A,AAAA,CAA,CNAME,HINFO,LOC,MX,NAPTR,NS,PTR,RP,SOA,SPF,SRV,TXT,MBOXFW}
	
	private String name;
	@Enumerated(EnumType.STRING)
	private TYPE type;
	private String content;
	private int ttl = 3600; //one hour
	private int prio;
	@XmlTransient
	private int zoneRecordId;
	private boolean active=true;
	private String orderName;
	private boolean auth=true;
	
	//mapping back to domain
	@ManyToOne()
	@XmlTransient
	private Domain domain;
	
	
	
	/* (non-Javadoc)
	 * @see com.nicmus.jpoweradmin.model.orm.PersistentObject#getId()
	 */
	@Override
	@XmlElement
	public int getId() {
		return super.getId();
	}
	/* (non-Javadoc)
	 * @see com.nicmus.jpoweradmin.model.orm.PersistentObject#setId(int)
	 */
	@Override
	protected void setId(int id) {
		super.setId(id);
	}
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * @return the type
	 */
	public TYPE getType() {
		return type;
	}
	/**
	 * @param type the type to set
	 */
	public void setType(TYPE type) {
		this.type = type;
	}
	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}
	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}
	/**
	 * @return the ttl
	 */
	public int getTtl() {
		return ttl;
	}
	/**
	 * @param ttl the ttl to set
	 */
	public void setTtl(int ttl) {
		this.ttl = ttl;
	}
	/**
	 * @return the prio
	 */
	public int getPrio() {
		return prio;
	}
	/**
	 * @param prio the prio to set
	 */
	public void setPrio(int prio) {
		this.prio = prio;
	}

	/**
	 * @return the zoneRecordId
	 */
	public int getZoneRecordId() {
		return zoneRecordId;
	}
	/**
	 * @param zoneRecordId the zoneRecordId to set
	 */
	public void setZoneRecordId(int zoneRecordId) {
		this.zoneRecordId = zoneRecordId;
	}
	/**
	 * @return the active
	 */
	public boolean isActive() {
		return active;
	}
	/**
	 * @param active the active to set
	 */
	public void setActive(boolean active) {
		this.active = active;
	}
	/**
	 * @return the orderName
	 */
	public String getOrderName() {
		return orderName;
	}
	/**
	 * @param orderName the orderName to set
	 */
	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}
	/**
	 * @return the auth
	 */
	public boolean isAuth() {
		return auth;
	}
	/**
	 * @param auth the auth to set
	 */
	public void setAuth(boolean auth) {
		this.auth = auth;
	}
	/**
	 * @return the domain
	 */
	
	public Domain getDomain() {
		return domain;
	}
	/**
	 * @param domain the domain to set
	 */
	public void setDomain(Domain domain) {
		this.domain = domain;
	}
	
	
	
}

src/main/java/com/nicmus/jpoweradmin/controller/AccountController.java
/*******************************************************************************
 * Copyright (C) 2019 nicmus inc. (jivko.sabev@gmail.com)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.nicmus.jpoweradmin.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.Locale;
import java.util.TimeZone;
import java.util.UUID;

import javax.annotation.PostConstruct;
import javax.annotation.security.RolesAllowed;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.Logger;

import com.nicmus.jpoweradmin.model.orm.CurrentUser;
import com.nicmus.jpoweradmin.model.orm.User;
import com.nicmus.jpoweradmin.model.orm.UserPreferences;
import com.nicmus.jpoweradmin.service.AccountServiceDAO;
import com.nicmus.jpoweradmin.service.GeneralDAO;

@Named
@ViewScoped
@RolesAllowed({"ROOT","USER"})
public class AccountController implements Serializable {
	
	private static final long serialVersionUID = 3455754276193901320L;

	@Inject
	private Logger logger;
	
	@Inject
	private UserPreferences userPreferences;
	
	@Inject
	private CurrentUser currentUser;
	
	@Inject
	private AccountServiceDAO accountServiceDAO;
	
	@Inject
	private GeneralDAO generalDAO;
	
	@Inject
	private FacesContext facesContext;
	
	private User user;
	
	private String confirmDelete;
	
	@PostConstruct
	public void loadSessionUser() {
		String name = this.currentUser.getUserName();
		this.user = this.accountServiceDAO.getUser(name);
	}
	
	/**
	 * Time zone
	 */
	public void timeZoneChanged() {
		String timeZoneId = this.userPreferences.getTimeZone().getID();
		String userName = this.currentUser.getUserName();
		this.userPreferences.setTimeZone(TimeZone.getTimeZone(timeZoneId));
		this.accountServiceDAO.updateTimeZonePreference(userName, timeZoneId);
		this.facesContext.addMessage(null, new FacesMessage("Time Zone Changed", "Time Zone Changed to " + timeZoneId));
	}
	
	/**
	 * Change the user locale
	 */
	public void localeChanged() {
		
		String localeName = this.userPreferences.getLocaleName();
		this.logger.info("Locale selected {}", localeName);
		String userName = this.currentUser.getUserName();
		Locale newLocale = Locale.forLanguageTag(localeName);
		this.userPreferences.setLocale(newLocale);
		this.logger.info("Locale changed to {}",newLocale.getDisplayName());
		this.facesContext.getViewRoot().setLocale(newLocale);
		this.accountServiceDAO.updateLocalePreferences(userName, localeName);
		this.facesContext.addMessage(null, new FacesMessage("Locale Changed", "Locale Changed to " + newLocale.getDisplayName()));
	}
	
	/**
	 * Save the user requested changes
	 */
	public void save() {
		this.generalDAO.update(this.user);
		this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,"User Preferences saved",""));
	}
	/**
	 * Reissue the API key for a user.
	 */
	public void reissueAPIKey() {
		this.logger.info("User name passed: {}", this.user.getUserName());
		this.user.setApikey(UUID.randomUUID().toString());
		this.generalDAO.update(user);
		this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "API Key reissued",""));
	}
	
	/**
	 * Delete action for the given user
	 * @return 
	 * @throws IOException 
	 */
	public String delete() throws IOException {
		if(this.confirmDelete == null || !this.confirmDelete.equalsIgnoreCase("yes")) {
			return null;
		}
		String userName = this.currentUser.getUserName();
		this.accountServiceDAO.deleteUserAccount(userName);
		Flash flash = this.facesContext.getExternalContext().getFlash();
		flash.setKeepMessages(true);
		this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "User marked for deletion",""));
		return "zones?faces-redirect=true";
	}

	/**
	 * @return the user
	 */
	public User getUser() {
		return this.user;
	}

	/**
	 * @param user the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * @return the confirmDelete
	 */
	public String getConfirmDelete() {
		return confirmDelete;
	}

	/**
	 * @param confirmDelete the confirmDelete to set
	 */
	public void setConfirmDelete(String confirmDelete) {
		this.confirmDelete = confirmDelete;
	}
	
	
}

src/main/java/com/nicmus/jpoweradmin/controller/AdminController.java
/*******************************************************************************
 * Copyright (C) 2017 nicmus inc. (jivko.sabev@gmail.com)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.nicmus.jpoweradmin.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.annotation.security.RolesAllowed;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

import com.nicmus.jpoweradmin.model.orm.CurrentUser;
import com.nicmus.jpoweradmin.model.orm.Role;
import com.nicmus.jpoweradmin.model.orm.User;
import com.nicmus.jpoweradmin.service.AccountServiceDAO;
import com.nicmus.jpoweradmin.service.ZoneImportService;

@Named
@ViewScoped
@RolesAllowed({"ROOT"})
public class AdminController implements Serializable {
	private static final long serialVersionUID = -1405453812063525934L;
	
	@Inject
	private AccountServiceDAO accountSericeDAO;
	
	@Inject
	private ZoneImportService zoneImportService;
	
	private LazyDataModel<User> userModel;
	
	@Inject
	private FacesContext facesContext;
	
	@Inject
	private CurrentUser currentUser;
	
	@PostConstruct
	public void init() {
		this.userModel = new LazyDataModel<User>() {
			private static final long serialVersionUID = -3991964307829678282L;

			/* (non-Javadoc)
			 * @see org.primefaces.model.LazyDataModel#load(int, int, java.lang.String, org.primefaces.model.SortOrder, java.util.Map)
			 */
			@Override
			public List<User> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters) {
				List<User> users = accountSericeDAO.getUsers(first, pageSize, sortField, sortOrder, filters);
				long userCount = accountSericeDAO.getUserCount(filters);
				this.setRowCount(Math.toIntExact(userCount));
				this.setWrappedData(users);
				return users;
			}
			
			
			
			/* (non-Javadoc)
			 * @see org.primefaces.model.LazyDataModel#getRowData(java.lang.String)
			 */
			@Override
			public User getRowData(String rowKey) {
				List<User> wrappedData = (List<User>) this.getWrappedData();
				for(User u : wrappedData) {
					if(u.getId() == Integer.parseInt(rowKey)) {
						return u;
					}
				}
				return null;
			}

			/* (non-Javadoc)
			 * @see org.primefaces.model.LazyDataModel#getRowKey(java.lang.Object)
			 */
			@Override
			public Object getRowKey(User object) {
				return object.getId();
			}
		};
	}

	/**
	 * @return the userModel
	 */
	public LazyDataModel<User> getUserModel() {
		return userModel;
	}

	/**
	 * @param userModel the userModel to set
	 */
	public void setUserModel(LazyDataModel<User> userModel) {
		this.userModel = userModel;
	}
	
	/**
	 * 
	 * @return
	 */
	public List<Role> getRoles(){
		return new ArrayList<>(this.userModel.getRowData().getRoles());
	}

	/**
	 * toggle the status of the user
	 */
	public void toggle() {
		User user = this.userModel.getRowData();
		String userName = user.getUserName();
		if(user.isDeleted()) {
			this.accountSericeDAO.disableUserAcount(userName);
			this.facesContext.addMessage(null,new FacesMessage(FacesMessage.SEVERITY_INFO, userName + " marked for deletion",""));
		} else {
			this.accountSericeDAO.reenableUserAccount(userName);
			this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, userName + " re-enabled",""));
		}
	}
	
	/**
	 * View the user account
	 * @return
	 */
	public String viewZone() {
		User rowData = this.userModel.getRowData();
		this.currentUser.setUserName(rowData.getUserName());
		return "zones?faces-redirect=true";		
	}
	
	/**
	 * 
	 */
	public void importZones() {
		int importZones = this.zoneImportService.importZones();
		this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, importZones + " zones imported into JPowerAdmin",""));
	}
}

src/main/java/com/nicmus/jpoweradmin/controller/PasswordChangeController.java
/*******************************************************************************
 * Copyright (C) 2019 nicmus inc. (jivko.sabev@gmail.com)
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.nicmus.jpoweradmin.controller;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.Logger;

import com.nicmus.jpoweradmin.model.orm.CurrentUser;
import com.nicmus.jpoweradmin.model.orm.Password;
import com.nicmus.jpoweradmin.service.PasswordChangeService;

@Named
@RequestScoped
public class PasswordChangeController {

	@Inject
	private FacesContext facesContext;
	
	@Inject
	private PasswordChangeService passwordChangeService;
	
	
	@Inject
	private Logger logger;
	
	@Inject
	private Password password;

	@Inject
	private CurrentUser currentUser;
	
	private String currentPassword;
	
	/**
	 * @return 
	 * 
	 */
	public String changePassword() {
		this.logger.info("Password {} - {}", this.getPassword().getPassword(), this.password.getConfirmPassword());
		//check to see if the old password matches
		//String userName = this.facesContext.getExternalContext().getUserPrincipal().getName();
		String userName = this.currentUser.getUserName();
		if(!this.passwordChangeService.passwordMatches(userName, this.getCurrentPassword())) {
			this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"The current password does not match",""));
			return null;
		}
		//check the new passwords match
		Password password = this.getPassword();
		if(!password.getPassword().equals(password.getConfirmPassword())) {
			this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"Passwords do not match",""));
			return null;
		}
		//update the password.
		this.passwordChangeService.changePassword(userName, password.getPassword());
		this.facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,"Password Changed",""));
		return "account";
	}

	/**
	 * @return the password
	 */
	public Password getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(Password password) {
		this.password = password;
	}

	/**
	 * @return the currentPassword
	 */
	public String getCurrentPassword() {
		return currentPassword;
	}

	/**
	 * @param currentPassword the currentPassword to set
	 */
	public void setCurrentPassword(String currentPassword) {
		this.currentPassword = currentPassword;
	}
	
	
	
}

src/main/webapp/members/account.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form id="userForm">
			<p:tabView id="userPreferences">
				<p:tab title="User Account">
					<h:panelGrid columns="1">
						<p:outputLabel for="firstName" value="First Name"></p:outputLabel>
						<p:inputText id="firstName" value="#{accountController.user.firstName}"></p:inputText>
						<p:message for="firstName"/>

						<p:outputLabel for="lastName" value="Last Name"></p:outputLabel>
						<p:inputText id="lastName" value="#{accountController.user.lastName}"></p:inputText>
						<p:message for="lastName"/>

						<p:outputLabel for="email" value="Email"></p:outputLabel>
						<p:inputText id="email" value="#{accountController.user.email}"></p:inputText>
						<p:message for="email"/>

						<p:outputLabel for="userName" value="User Name"></p:outputLabel>
						<p:inputText id="userName" value="#{accountController.user.userName}" readonly="true" disabled="true"></p:inputText>
						<p:message for="userName"/>

						<p:outputLabel for="password" value="Password&#160;">
							<p:link value="Change" href="passwordchange.jsf"></p:link>
						</p:outputLabel>
						<h:inputSecret id="password" value="Nice Try But No Cigar" redisplay="true" readonly="true"/>

						<h:outputLabel for="apiKey" value="API Key &#160;">
							<p:commandLink value="New" action="#{accountController.reissueAPIKey()}" update="apiKey"></p:commandLink>
						</h:outputLabel>
						<h:outputText id="apiKey" value="#{accountController.user.apikey}"/>

						<p:spacer/>

						<h:outputText value="Date Created"/>
						<h:outputText id="dateCreated" value="#{accountController.user.dateCreated}" >
							<f:convertDateTime type="both" timeZone="#{userPreferences.timeZone}" locale="#{userPreferences.locale}"/>
						</h:outputText>

						<p:spacer/>

						<h:outputText value="Date Modified"/>
						<h:outputText id="dateModified" value="#{accountController.user.dateModified}">
							<f:convertDateTime type="both" timeZone="#{userPreferences.timeZone}" locale="#{userPreferences.locale}"/>
						</h:outputText>

						<p:spacer/>

						<p:commandLink value="Delete Account" onclick="PF('accountDialogue').show();"></p:commandLink>
					</h:panelGrid>
				</p:tab>

				<p:tab title="Locale Preferences">
					<h:panelGrid columns="1">
						<p:outputLabel for="timeZoneId" value="TimeZone"/>
						<p:selectOneMenu id="timeZoneId" value="#{userPreferences.timeZone.ID}">
							<p:ajax event="change" listener="#{accountController.timeZoneChanged}"></p:ajax>
							<f:selectItems value="#{timeZones}"></f:selectItems>
						</p:selectOneMenu>

						<p:outputLabel for="localeId" value="Locale"/>
						<p:selectOneMenu id="localeId" value="#{userPreferences.localeName}">
							<p:ajax event="change" listener="#{accountController.localeChanged}"/>
							<f:selectItems var="locale" value="#{locales}" itemValue="#{locale.language}-#{locale.country}" itemLabel="#{locale.displayName}" />
						</p:selectOneMenu>
					</h:panelGrid>
				</p:tab>
			</p:tabView>

			<p:commandButton value="Save Changes" action="#{accountController.save}" ajax="no"></p:commandButton>

			<p:dialog header="Confirm account removal" widgetVar="accountDialogue" modal="true">
				<p>Enter the word "YES" in the text input field below and submit the from.</p>

				<p:panel>
					<h:panelGrid columns="1">
						<p:outputLabel for="confirmDeleteBox" value="Are you sure?"></p:outputLabel>
						<p:inputText id="confirmDeleteBox" value="#{accountController.confirmDelete}"></p:inputText>
					</h:panelGrid>
				</p:panel>

				<p:commandButton value="Delete Account" action="#{accountController.delete}" ajax="no" oncomplete="PF('accountDialogue').hide();"></p:commandButton>
			</p:dialog>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/members/accounts.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form id="accountForm">
			<p:dataTable id="accountTable"
				var="user"
				value="#{adminController.userModel}"
				rowKey="#{user.id}"
				lazy="true"
				resizableColumns="true"
				paginator="true"
				rows="30"
				paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
				paginatorPosition="bottom"
				paginatorAlwaysVisible="false">

				<f:facet name="header">Accounts</f:facet>

				<p:column filterBy="#{user.userName}" filterMatchMode="contains" headerText="Name" sortBy="#{user.userName}">
					<p:commandLink value="#{user.userName}" action="#{adminController.viewZone}"></p:commandLink>
				</p:column>

				<p:column headerText="Deleted" style="text-align:center;width:6%;" sortBy="#{user.deleted}">
					<p:inputSwitch value="#{user.deleted}">
						<p:ajax listener="#{adminController.toggle}" update="accountTable"></p:ajax>
					</p:inputSwitch>
				</p:column>

				<p:column headerText="Role">
					<ui:repeat var="r" value="#{adminController.roles}">
						#{r.role.toString()}
					</ui:repeat>
				</p:column>

				<p:column headerText="Date Created" sortBy="#{user.dateCreated}">
					<h:outputText value="#{user.dateCreated}" >
						<f:convertDateTime type="both"  timeZone="#{userPreferences.timeZone}" locale="#{userPreferences.locale}"/>
					</h:outputText>
				</p:column> 

				<p:column headerText="Date Modified" sortBy="#{user.dateModified}">
					<h:outputText value="#{user.dateModified}">
						<f:convertDateTime type="both"  timeZone="#{userPreferences.timeZone}" locale="#{userPreferences.locale}"/>
					</h:outputText>
				</p:column>
			</p:dataTable>
		</h:form>

		<p:spacer/>

		<h:form>
			<p:panel header="Zone Import">
				<h3>Zone Import from PowerDNS</h3>

				<p>Click on the Start button to import zones from PowerDNS to JPowerAdmin.
				Imported zones are linked to all accounts having ROOT privileges.</p>

				<p:commandButton value="Start" action="#{adminController.importZones}"></p:commandButton>
			</p:panel>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/members/passwordchange.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<p><p:link value="&#171; Back To Account" outcome="account"></p:link></p>

		<h:form>
			<p:panel header="Password Change">
				<h:panelGrid columns="1">
					<p:outputLabel for="currentPassword" value="Current Password"></p:outputLabel>
					<p:password id="currentPassword" value="#{passwordChangeController.currentPassword}" required="true"></p:password>

					<p:outputLabel for="newPassword" value="New Password"></p:outputLabel>
					<p:password id="newPassword" value="#{passwordChangeController.password.password}" required="true" match="confirmPassword"></p:password>

					<p:outputLabel for="confirmPassword" value="Confirm New Password"></p:outputLabel>
					<p:password id="confirmPassword" value="#{passwordChangeController.password.confirmPassword}" required="true"></p:password>
				</h:panelGrid>
			</p:panel>

			<p:commandButton value="Change Password" action="#{passwordChangeController.changePassword}" ajax="no"></p:commandButton>
		</h:form>
	</ui:define>
</ui:composition>